version: '3.8'

services:
  mariadb:
    image: mariadb:11.7
    hostname: mariadb
    restart: always
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: recettes_db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - my_networks

  recettes-api:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - app.env
    networks:
      - my_networks

networks:
  my_networks:
